In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yaml
import numpy as np
import sklearn

In [2]:
# import the dataset
with open('../config.yaml', 'r') as file:
    config = yaml.safe_load(file)
df = pd.read_csv(config["input_data"]["file_1"])

In [8]:
# check quickly data content
print(df.shape)
print(df.isnull().sum())
print(df.dtypes)
print(df.select_dtypes("str").nunique().sort_values(ascending=False))

(2111, 17)
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64
Gender                                str
Age                               float64
Height                            float64
Weight                            float64
family_history_with_overweight        str
FAVC                                  str
FCVC                              float64
NCP                               float64
CAEC                                  str
SMOKE                                 str
CH2O                              float64
SCC                                   str
FAF                               float64
TUE                               float64
CALC                                  str
MTRANS                                str
NObeyesdad                            str
dtype: object
NObeyesdad                        7
MTRANS                            5
CAEC                              4
CALC                              4
Gender                            2
SMOKE                             2
FAVC                              2
family_history_with_overweight    2
SCC                               2
dtype: int64

In [ ]:


# predictions - array - and real values
pred = knn.predict(X_test)
y_test.values

# list of uncorrect predictions
import numpy as np
np.where(pred != y_test.values) # reach the index number of the rows that failed

# accuracy
print(f"The accuracy the model is {knn.score(X_test, y_test)*100: .2f}%")

In [44]:
# categorical variables
features = df.select_dtypes(include="str")
features.head(2)

# X-y split; features = X, target = y
x = df.drop(columns = ["NObeyesdad"])
y = df["NObeyesdad"]

# encoding features to get only numerical values
x = pd.get_dummies(x, drop_first=True)

# encoding target too
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

# preparing the train and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0) # 0-999

# create an instance classifier for the model
from sklearn.neighbors import KNeighborsClassifier

# define the number of neighbours threshold
knn = KNeighborsClassifier(n_neighbors=3) # 5 is the value by default

# train the model
knn.fit(X_train, y_train)

# predictions - array - and real values
pred = knn.predict(X_test)
y_test # here test values just need to write test because not a serie

array([3, 2, 5, 4, 4, 3, 0, 4, 2, 3, 4, 2, 5, 2, 1, 2, 1, 4, 6, 6, 4, 2,
       2, 6, 2, 3, 4, 6, 5, 3, 5, 6, 6, 2, 3, 5, 6, 0, 5, 0, 5, 6, 0, 5,
       4, 3, 2, 0, 4, 0, 5, 3, 3, 5, 2, 2, 5, 5, 3, 1, 2, 1, 2, 0, 0, 3,
       1, 5, 5, 2, 6, 4, 3, 2, 2, 1, 2, 5, 3, 0, 6, 5, 2, 5, 6, 1, 1, 3,
       4, 3, 5, 0, 0, 3, 6, 4, 2, 3, 3, 3, 0, 2, 0, 5, 4, 2, 6, 4, 5, 6,
       0, 5, 2, 1, 2, 6, 2, 2, 6, 0, 2, 4, 0, 1, 4, 6, 2, 5, 6, 5, 1, 0,
       1, 2, 6, 4, 5, 3, 4, 3, 6, 6, 1, 0, 0, 1, 6, 6, 2, 0, 6, 5, 4, 4,
       4, 2, 2, 1, 3, 5, 2, 4, 6, 4, 0, 0, 3, 2, 5, 4, 5, 3, 4, 1, 5, 3,
       2, 0, 1, 3, 5, 2, 4, 4, 4, 0, 5, 5, 3, 4, 2, 6, 3, 6, 1, 4, 3, 3,
       2, 5, 1, 0, 5, 5, 2, 6, 2, 2, 2, 0, 5, 1, 1, 3, 3, 6, 5, 4, 6, 4,
       3, 2, 1, 0, 4, 4, 1, 6, 5, 0, 4, 4, 5, 4, 0, 3, 1, 5, 2, 4, 2, 0,
       4, 4, 1, 1, 0, 4, 6, 6, 2, 5, 6, 4, 1, 4, 0, 4, 2, 1, 4, 1, 1, 1,
       0, 2, 3, 0, 1, 4, 6, 2, 4, 1, 6, 2, 1, 1, 1, 6, 2, 1, 0, 1, 6, 5,
       2, 4, 6, 4, 4, 3, 1, 4, 4, 5, 1, 1, 4, 4, 0, 1, 1, 0, 6, 4, 5, 0,
       0, 0, 5, 0, 2, 0, 3, 3, 4, 0, 1, 0, 3, 2, 4, 6, 4, 6, 2, 0, 0, 1,
       1, 5, 0, 0, 1, 0, 0, 0, 3, 5, 2, 5, 1, 0, 0, 6, 5, 2, 6, 1, 0, 3,
       4, 5, 3, 6, 2, 6, 3, 5, 3, 0, 2, 4, 6, 0, 2, 4, 0, 4, 3, 4, 1, 0,
       6, 2, 1, 2, 4, 0, 0, 4, 5, 6, 3, 2, 0, 1, 0, 3, 6, 1, 3, 3, 6, 1,
       2, 1, 5, 2, 0, 6, 4, 2, 5, 1, 4, 0, 2, 6, 6, 4, 5, 3, 0, 5, 6, 5,
       1, 3, 4, 3, 3])

In [40]:
# visualize wront predictions
import numpy as np
np.where(pred != y_test) # reach the index number of the rows that failed

(array([ 12,  16,  27,  28,  31,  57,  61,  66,  75,  85,  86, 123, 125,
        130, 132, 143, 145, 157, 162, 178, 187, 194, 199, 211, 212, 227,
        237, 244, 245, 249, 254, 262, 274, 275, 276, 283, 285, 292, 296,
        304, 318, 323, 344, 348, 376, 390, 391, 399, 405, 412]),)

In [35]:
# check the real and predicted data
comparison = pd.DataFrame({
    "Real": y_test,
    "Pred": pred
})

comparison.head(10)

   Real  Pred
0     3     3
1     2     2
2     5     5
3     4     4
4     4     4
5     3     3
6     0     0
7     4     4
8     2     2
9     3     3

In [43]:
# come back to the previous labelling (categorical)
real_labels = le.inverse_transform(y_test)
pred_labels = le.inverse_transform(pred)

comparison = pd.DataFrame({
    "Real": real_labels,
    "Pred": pred_labels
})

comparison.head(10)

                  Real                 Pred
0      Obesity_Type_II      Obesity_Type_II
1       Obesity_Type_I       Obesity_Type_I
2   Overweight_Level_I   Overweight_Level_I
3     Obesity_Type_III     Obesity_Type_III
4     Obesity_Type_III     Obesity_Type_III
5      Obesity_Type_II      Obesity_Type_II
6  Insufficient_Weight  Insufficient_Weight
7     Obesity_Type_III     Obesity_Type_III
8       Obesity_Type_I       Obesity_Type_I
9      Obesity_Type_II      Obesity_Type_II

In [42]:
# check the uncorrect predictions

print(f"The accuracy the model is {knn.score(X_test, y_test)*100: .2f}%")

The accuracy the model is  88.18%